spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/fin_alert
spring.datasource.username=prana
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
